from django.db import models
from django.contrib.auth.models import User

# Venue type model, generally a bar, brewery, or store
class VenueType(models.Model):
    slug = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Venue Types"

# Venue model
class Venue(models.Model):
    slug = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    address1 = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    post_code = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    phone = models.CharField(max_length=20, null=True, blank=True)
    website = models.CharField(max_length=100)
    notes = models.TextField(null=True, blank=True)
    venue_type = models.ForeignKey(VenueType)
    foursquare_id = models.CharField(max_length=255, null=True, blank=True)
    lat = models.DecimalField(decimal_places=8, max_digits=11, null=True, blank=True)
    lon = models.DecimalField(decimal_places=8, max_digits=11, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Venues"

# Venue tip model, generated by users    
class VenueTip(models.Model):
    text = models.CharField(max_length=140)
    added_by = models.ForeignKey(User)
    venue = models.ForeignKey(Venue)
    created = models.DateField(auto_now_add=True)
    
    def __unicode__(self):
        return self.text
    
    class Meta:
        verbose_name_plural = "Venue Tips"
